package com.ntando.ivu.data.entity

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Represents a user achievement entity within the IVU application local Room database.
 *
 * Tracks milestones unlocked or pursued by a user (e.g. streaks, reviews completed, journal entries written).
 * Indexed by [userId] for fast querying of achievements owned by a specific user.
 *
 * @property id The unique auto-generated primary key for this achievement record.
 * @property userId Identifier linking this achievement to a specific user.
 * @property title Display title of the achievement.
 * @property description Detailed explanation of the achievement's unlocking criteria.
 * @property icon Resource or asset identifier string representing the achievement icon.
 * @property isUnlocked Flag indicating whether the user has unlocked this achievement.
 * @property dateUnlocked Timestamp in epoch milliseconds when unlocked, or `null` if locked.
 * @property isNotified Flag indicating if the user has been notified of this unlock event.
 */
@Entity(
    tableName = "achievements",
    indices = [Index(value = ["userId"])]
)
data class Achievement(
    /** Primary key auto-generated by Room database. */
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    /** Unique user identifier owning this achievement. */
    val userId: String,
    /** Title describing the achievement. */
    val title: String,
    /** Description explaining criteria to unlock the achievement. */
    val description: String,
    /** Icon asset name or identifier string. */
    val icon: String,
    /** Whether the achievement is currently unlocked by the user. */
    val isUnlocked: Boolean = false,
    /** Epoch timestamp in milliseconds when achievement was unlocked, or null if locked. */
    val dateUnlocked: Long? = null,
    /** Whether an in-app or system notification has been displayed for unlocking this. */
    val isNotified: Boolean = false
)
