package com.ntando.ivu.data.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Enumeration of supported primary languages for study decks and flashcards.
 */
enum class Language {
    /** English language setting. */
    EN,
    /** isiZulu language setting. */
    ZU,
    /** Afrikaans language setting. */
    AF
}

/**
 * Represents a collection or deck of flashcards stored in the Room database.
 *
 * Each deck belongs to an owner user ([ownerId]) and contains a cached card count.
 *
 * @property deckId Primary key auto-generated by Room.
 * @property remoteId Optional cloud/server ID for synchronization.
 * @property ownerId Database ID of the user who owns this deck.
 * @property title Name or title of the deck.
 * @property language Target [Language] setting for flashcards within this deck.
 * @property cardCount Cached total number of flashcards contained in this deck.
 * @property createdAt Epoch timestamp in milliseconds when deck was created.
 */
@Entity(tableName = "decks")
data class Deck(
    /** Unique primary key ID for the deck. */
    @PrimaryKey(autoGenerate = true) val deckId: Long = 0,
    /** Optional identifier for backend remote database synchronization. */
    val remoteId: String? = null,
    /** Primary key ID of the user owning this deck. */
    val ownerId: Long,
    /** Display title of the flashcard deck. */
    val title: String,
    /** Study language assigned to this deck. */
    val language: Language,
    /** Cached number of cards stored in this deck. */
    val cardCount: Int = 0,
    /** Epoch timestamp in milliseconds indicating deck creation date. */
    val createdAt: Long = System.currentTimeMillis()
)
