package com.ntando.ivu.data.entity

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Represents an individual study flashcard entity stored within a [Deck].
 *
 * Configured with SuperMemo SM-2 algorithm variables ([easeFactor], [intervalDays], [repetitions], [dueDate])
 * to support spaced-repetition study routines.
 *
 * Foreign key relationship automatically cascade-deletes flashcards when their parent [Deck] is deleted.
 *
 * @property cardId Primary key auto-generated by Room.
 * @property remoteId Optional cloud backend sync ID.
 * @property deckId Foreign key reference to the parent [Deck.deckId].
 * @property frontText Prompt or question displayed on front side.
 * @property backText Solution or answer displayed on back side.
 * @property imageUrl Optional local URI or web URL pointing to an associated image.
 * @property easeFactor Spaced repetition ease factor (defaults to `2.5f`).
 * @property intervalDays Scheduled review interval in days.
 * @property repetitions Consecutive successful review count.
 * @property dueDate Epoch timestamp in milliseconds when card is next due for review.
 */
@Entity(
    tableName = "flashcards",
    foreignKeys = [
        ForeignKey(
            entity = Deck::class,
            parentColumns = ["deckId"],
            childColumns = ["deckId"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [Index(value = ["deckId"])]
)
data class Flashcard(
    /** Primary key auto-generated by Room database. */
    @PrimaryKey(autoGenerate = true) val cardId: Long = 0,
    /** Optional backend sync identifier. */
    val remoteId: String? = null,
    /** Foreign key linking card to parent deck. */
    val deckId: Long,
    /** Prompt or word on the card front. */
    val frontText: String,
    /** Answer or translation on the card back. */
    val backText: String,
    /** Optional image URL or file path associated with card. */
    val imageUrl: String? = null,
    /** Ease factor used for SM-2 spaced repetition calculations. */
    val easeFactor: Float = 2.5f,
    /** Current scheduled review interval in days. */
    val intervalDays: Int = 0,
    /** Count of consecutive successful review attempts. */
    val repetitions: Int = 0,
    /** Epoch timestamp in milliseconds when next review is scheduled. */
    val dueDate: Long = System.currentTimeMillis()
)
