package com.ntando.ivu.data.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Enumeration representing mood states recorded during journal reflections.
 */
enum class Mood {
    /** Positive mood state. */
    GREAT,
    /** Neutral mood state. */
    OKAY,
    /** Challenging mood state. */
    TOUGH
}

/**
 * Represents a personal reflection or journal entry created by a user.
 *
 * Allows users to track learning progress, document thoughts, record emotional state ([Mood]),
 * and optionally associate reflections with a study [Deck].
 *
 * @property entryId Primary key auto-generated by Room database.
 * @property remoteId Optional server synchronization identifier.
 * @property userId Identifier of user owning this entry.
 * @property date Epoch timestamp in milliseconds when entry was recorded.
 * @property mood The [Mood] state recorded for this entry.
 * @property text Body text content of the journal reflection.
 * @property linkedDeckId Optional foreign key reference to a related [Deck].
 */
@Entity(tableName = "journal_entries")
data class JournalEntry(
    /** Primary key auto-generated by Room database. */
    @PrimaryKey(autoGenerate = true) val entryId: Long = 0,
    /** Optional remote backend identification string. */
    val remoteId: String? = null,
    /** Unique user string ID owning this journal entry. */
    val userId: String,
    /** Creation timestamp in epoch milliseconds. */
    val date: Long = System.currentTimeMillis(),
    /** Selected mood state associated with entry. */
    val mood: Mood,
    /** Written narrative text of journal entry. */
    val text: String,
    /** Optional reference to a related deck ID. */
    val linkedDeckId: Long? = null
)
