package com.ntando.ivu.data.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a user profile entity stored in the IVU local Room database.
 *
 * Stores core account information including credentials and display details.
 *
 * @property id Primary key auto-generated by Room database.
 * @property name User's full display name.
 * @property email Primary email address associated with user account.
 * @property password User account password string.
 */
@Entity(tableName = "users")
data class User(
    /** Primary key auto-generated by Room. */
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    /** Full display name of the user. */
    val name: String,
    /** User email address used for login and user context. */
    val email: String,
    /** Password string for local user authentication. */
    val password: String = ""
)
