package com.ntando.ivu.data.model

/**
 * Non-persistent model representing a single conversational message in the AI chatbot screen.
 *
 * @property text Content string of the chat message.
 * @property isUser `true` if message originated from user, `false` if generated by AI assistant.
 */
data class ChatMessage(
    /** Body text of message. */
    val text: String,
    /** Flag indicating whether sender is user (`true`) or AI assistant (`false`). */
    val isUser: Boolean
)
